services:
  - type: web
    name: quicklink
    env: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: GO_VERSION
        value: "1.21"
    healthCheckPath: /
    autoDeploy: true
    repo: https://github.com/Neorex80/Quick-Link
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
